### ISSUE TITLE
read.tagged should support format = "obj"

### ISSUE THREAD

**Issue by dorvak** [unDocUMeantIt/koRpus#1]
The read.tagged function should accept vectors and other objects, not just files.

**Comment by unDocUMeantIt** [comment]
thanks, sounds reasonable.

the only thing that keeps me from implementing this is what you might mean by "other objects"? since TreeTagger returns its output in three character columns, i think matrix or data.frame objects are the obvious candidates here. how would you like to put that into a vector, though?

**Comment by dorvak** [comment]
Sorry, that was a little bit unprecise. At least for me, vectors with tagged strings are completely sufficient [Background: Stored tree-tagged text (via Pythons TreeTagger-Module) in a MongoDB and would like to read them in to R again]. I tried to mimic the behaviour of the `treetagger`-Function, which works with vectors, but I couldn't manage to include it into the package namespace afterwards (no experience in developing R-packages, unfortunately)

**Comment by unDocUMeantIt** [comment]
you mean `treetag(..., format="obj")`, right? that one can take a single vector as the text to be tagged. but if the text _is_ already tagged, it would have _three_ columns (token, tag, lemma). with this assumption in mind, you could indeed make it work with a vector, but for my taste it would be much clearer if you turned the vector into a three column matrix first and prepare `read.tagged()` to accept matrix/data.frame objects.

but maybe i'm not seeing the obvious -- can you give a short example for a vector you have in mind?

as for the packaging process, you might like to have a look at [roxyPackge](http://reaktanz.de/?c=hacking&s=roxyPackage) (has an introducing [vignette](http://r.reaktanz.de/pckg/roxyPackage/roxyPackage_vignette.pdf) and [presentation](https://osf.io/x8udj/)).

**Comment by dorvak** [comment]
Yeah, i might just convert my char-vector to a matrix/data-frame beforehand. Basically, the vector is just a tab-delimited raw output of the TreeTagger, like [here](https://gist.githubusercontent.com/dorvak/2c2716458d5bf9d662d5/raw/c4d1c41312ae98a9730f52fd492aa92e455dbf31/treetaged).

**Comment by unDocUMeantIt** [comment]
should work now in the develop branch -- can you check it out? e.g.

```
library(devtools)
install_github("unDocUMeantIt/koRpus", ref="develop")
```

if this works for you, i'll close the issue.
