### ISSUE TITLE
download of package ‘koRpus.lang.de’ failed

### ISSUE THREAD

**Issue by chrgrill** [unDocUMeantIt/koRpus#14]
I am trying to run the following script: 

`tagged = treetag("message.txt", treetagger=".../treetagger/cmd/tree-tagger-german", lang="de",
                 TT.options=list(tokenizer = "tree-tagger-german" , tagger = "tree-tagger" , params = "german-utf8.par" ) ,
                 format = "file" , stopwords=stopwords::stopwords("de", source = "stopwords-iso"))`

Since today, I get the following error message: 

> Error: Unknown tag definition requested: de

The command "available.koRpus.lang()" tells me that I have not installed "koRpus.lang.de"

When running "install.koRpus.lang("de")" or "install.packages("koRpus.lang.de", repos="https://undocumeantit.github.io/repos/l10n/")": I get the following error message:

> There are binary versions available but the source versions are later:
               binary source needs_compilation
sylly.de        0.1-2  0.1-3             FALSE
koRpus.lang.de  0.1-1  0.1-2             FALSE
> installing the source packages ‘sylly.de’, ‘koRpus.lang.de’
> trying URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/sylly.de_0.1-3.tar.gz'
Warning in install.packages :
  cannot open URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/sylly.de_0.1-3.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/sylly.de_0.1-3.tar.gz'
Warning in install.packages :
  download of package ‘sylly.de’ failed
trying URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/koRpus.lang.de_0.1-2.tar.gz'
Warning in install.packages :
  cannot open URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/koRpus.lang.de_0.1-2.tar.gz': HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://undocumeantit.github.io/repos/l10n/src/contrib/koRpus.lang.de_0.1-2.tar.gz'
Warning in install.packages :
  download of package ‘koRpus.lang.de’ failed

I also tried installing other languages like Spanish, French or Italian, but I always get the same error message.

I work with R version 3.5.1  on a Mac (macOS Mojave Version 10.14)

**Comment by unDocUMeantIt** [comment]
thank you for reporting this. the package index of the repository was broken and listed versions not yet released. should be fixed now, please try again.

**Comment by chrgrill** [comment]
works perfectly now! thx for your quick response
