### ISSUE TITLE
Error: Manual TreeTagger configuration: "en" is not a valid preset!

### ISSUE THREAD

**Issue by dong87** [unDocUMeantIt/koRpus#15]
run examples with 
```
tagged.results <- treetag("C:/my.data/speech.txt", treetagger="manual", lang="en",
   TT.options=list(path="C:/treetagger/", preset="en"))
```
arised this issue.

Windows 7, R 3.5.1

**Comment by unDocUMeantIt** [comment]
did you do `library(koRpus.lang.en)` first?

in koRpus >= 0.11-2, language support was moved into separate packages. see the message when koRpus is loaded regarding `?available.koRpus.lang` and `?install.koRpus.lang`

**Comment by JasonScottSchneider** [comment]
I am having the same problem. I tried loading the library(koRpus.lang.en), but this didn't help me. Furthermore, I made sure to set the path to where I have the folder for TreeTagger in the batches and environmental variables.
![korpus](https://user-images.githubusercontent.com/43894195/52159477-b2d1e600-266a-11e9-8a41-a82e1c499b37.jpg)
