### ISSUE TITLE
No S3 method for read.udhr

### ISSUE THREAD

**Issue by mekkim** [unDocUMeantIt/koRpus#2]
Function guess.lang attempts to call read.udhr to read the zip file.  There is no read.udhr S3 method, so it fails.

**Comment by unDocUMeantIt** [comment]
which version of koRpus are you using? there was an issue with guess.lang() reported to me a few weeks ago, that was triggered by the UDHR index files using a new format now. i (hopefully) fixed that in the develop branch of koRpus. to check it out:

```
library(devtools)
install_github("unDocUMeantIt/koRpus", ref="develop")
```

could you try if this solves the problem for you? if not, it would be helpful if you posted the full error message.

**Comment by mekkim** [comment]
Thanks for the quick response.

I had previously tried it with release (0.05-6) and dev (0.06-3).  The error was simply "read.udhr not found".  However, your latest github dev version (0.06-4) seems to work fine, though I still can't find the read.udhr() function.

Line 73 in guess.lang is (https://github.com/unDocUMeantIt/koRpus/blob/develop/R/guess.lang.R#L73) is read.udhr(udhr.path, quiet=quiet) - Where is it getting the read.udhr() function?

I ask because I'd like to modify it for my research so that it can take any zip file of texts, not just the udhr one (which I will happilyy submit as a pull request once it's done).

Great package!  ^_^

**Comment by mekkim** [comment]
Ah, I found it in https://github.com/unDocUMeantIt/koRpus/blob/develop/R/koRpus-internal.R#L936 - My bad.  I guess everything is fine.  Sorry to bother! :)

**Comment by unDocUMeantIt** [comment]
yes, read.udhr() is an internal function of the package, you can check for its 
existance by calling koRpus:::read.udhr() -- it should throw an error that 
"txt.path" is missing.

the method should work with any collection of text, given that there is a means to specify the language name. guess.lang() uses some of the structured information from the XML index file -- probably the easiest way to do this would be to structure your .zip file similar to the UDHR archive and include a matching index file -- then guess.lang() should just be fine with it, and you wouldn't have to patch the code. you could, however, write an R function that creates the archive, e.g. from a list of attributes. that would be neat ;-)

can the issue be closed?

**Comment by mekkim** [comment]
That's an excellent idea.  My intent is to write a function that dynamically creates an archive from texts passed to it, and then can be used to "guess" at categorizing other texts, similar to what is done in package:textcat, but using the zip compare method instead of n-gram comparisons.  I'll structure the zip file in the same way as the udhr file with the index and then write wrapper functions.  I'll submit a pull request if I can get it to work properly. :)

Yes, the issue can be closed as type invalid.  My mistake.  Thanks again for the quick response and discussion!

P.S. I didn't notice the third ":" in that command.  Again, my mistake.  I have learned once more.  Thanks for your patience! :)

**Comment by unDocUMeantIt** [comment]
always nice to get feedback and learn about new use cases.
