### ISSUE TITLE
Error: Specified directory cannot be found:  ~/bin/treetagger/bin

### ISSUE THREAD

**Issue by michperdomo** [unDocUMeantIt/koRpus#21]
It seems that no matter where I place the document files, I continue to receive the same error in R: 

`Error: Specified directory cannot be found:
 ~/bin/treetagger/bin`

The code I am using is below. I have installed TreeTagger using the terminal with no errors.

`tagged.text <- treetag(
  "sample_text.txt",
  treetagger="manual",
  lang="en",
  TT.options=list(
    path="~/bin/treetagger",
    preset="en"
  ),
  doc_id="sample"
)`

Can anyone help with this issue?

**Comment by unDocUMeantIt** [comment]
it's a bit hard to say without knowing anything about your setup, but does the directory `~/bin/treetagger/bin` actually exist? if "directory cannot be found" comes up, it usually means you need to check your TreeTagger location. a correct TreeTagger installation would also contain a `bin` directory below it's root directory.

assuming you're using GNU/linux, what does the command `ls -l ~/bin/treetagger` show?

**Comment by michperdomo** [comment]
This is what I get with the following:

```
PSY-078GG7:~ dwlab$ ls -l Desktop/TreeTagger/bin
total 440
```
`-rwxr-xr-x@ 1 dwlab  staff  72940 Apr  8  2019 train-tree-tagger`
`-rwxr-xr-x@ 1 dwlab  staff  75028 Apr  8  2019 tree-tagger`
`-rwxr-xr-x@ 1 dwlab  staff  71052 Apr  8  2019 tree-tagger-flush
`
But even if I use ~Desktop/TreeTagger/bin/tree-tagger, I get the same error.
`tagged.text <- treetag(`
`   "sample_text.txt",`
`   treetagger="manual",`
`   lang="en",`
`   TT.options=list(`
`     path="~Desktop/TreeTagger/bin/tree-tagger",`
`     preset="en"`
`   ),`
`   doc_id="sample"`
` )`
```
Error: Specified directory cannot be found:
 ~Desktop/TreeTagger/bin/tree-tagger/bin
```

**Comment by unDocUMeantIt** [comment]
looks like you have installed TreeTagger to `Desktop/TreeTagger`, you shouldn't point `treetag()` to `~/bin/treetagger`.
also, you must not omit a `/` after `~` because `~Desktop` will be interpreted as a directory with a tilde as it's first character, but `~/Desktop` means the directory `Desktop` in your home directory, which is what you want.

so using `path="~/Desktop/TreeTagger"` should do the trick.

**Comment by michperdomo** [comment]
That did the trick! Thanks so much.
