### ISSUE TITLE
Working in Python?

### ISSUE THREAD

**Issue by RomanADavis** [unDocUMeantIt/koRpus#27]
It looked liked koRpus had really good lemmatization functionality, but I'm working in Python. Is there a good python wrapper for this? Or is it derived from something that might have a python wrapper?

**Comment by unDocUMeantIt** [comment]
the lemmatization you see in `koRpus`' results is actually done by [TreeTagger](https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/), as `treetag()` basically is an R wrapper for that POS tagger. there also seems to be a [python wrapper](https://perso.limsi.fr/pointal/doku.php?id=dev:treetaggerwrapper).
