### ISSUE TITLE
option lexicon

### ISSUE THREAD

**Issue by agnesevardanega** [unDocUMeantIt/koRpus#28]
I'm trying to apply an auxiliary lexicon (lexicon = "namefile.txt"), but there is a bug in the function (I suppose), because the path is written as follows:

C:\TreeTagger\lib/file.txt

Therefore, in Windows, when the file does exist in the folder, I receive the error;

Error in file.info(x, extra_cols = FALSE) : argomento 'filename' non valido (non valid filename).

Thank you

**Comment by unDocUMeantIt** [comment]
hi agnes,
can you tell me which version of `koRpus` you are using?

**Comment by agnesevardanega** [comment]
Version 0.13-3, thx

(Inviato dal mio iPhone)

**Comment by unDocUMeantIt** [comment]
thanks for reporting this, i did find and fix an issue with lexicon files.

however, i was actually not able to replicate your problem (windows 10, using `koRpus.lang.en`).

could you please try to update to the develop version and try again:

```R
devtools::install_github("unDocUMeantIt/koRpus", ref="develop")
```

if the problem persists, can you tell me which language package (including its version number) you are using?

**Comment by agnesevardanega** [comment]
I use the italian language pack, which it is actually quite old. Windows 10, me too.

I’ll try the develop version and tell you.

(Inviato dal mio iPhone)

**Comment by unDocUMeantIt** [comment]
all language packages were updated a few weeks ago, you should probably upgrade that as well.

also, try using `file.path("C:", "TreeTagger")` to set the TreeTagger path.

**Comment by agnesevardanega** [comment]
It does work, even with “C:\TreeTagger”. Thx.


(Inviato dal mio iPhone)
