### ISSUE TITLE
Treetagger do not worh in both koRpus and teststem packages

### ISSUE THREAD

**Issue by oguzozbay** [unDocUMeantIt/koRpus#29]
I installed treetagger but I get an error message in both textstem and KoRpus packages for below codes:
Would you please help me.

#first example:
Error for koRpus package is as below:

Error in is_grouped_df(tbl) :  "TT.res" adında bir slot yok ("kRp.text" sınıfında bir nesne için)
TRANSLATION in English= 
Error in is_grouped_df(tbl) :  "TT.res" slot missing (for "kRp.text" class object)

#second example
library(textstem)
x <- c(
  'the dirtier dog has eaten the pies',
  'that shameful pooch is tricky and sneaky',
  "He opened and then reopened the food bag",
  'There are skies of blue and red roses too!')
lemma_dictionary2 <- make_lemma_dictionary(x, engine = 'treetagger')

ERROR: Error in dplyr::filter(tagged.results@TT.res[c("token", "lemma")], !lemma %in%  : 
  "TT.res" adında bir slot yok ("kRp.text" sınıfında bir nesne için)

**Comment by unDocUMeantIt** [comment]
see https://github.com/unDocUMeantIt/koRpus.lang.en/issues/1#issuecomment-755713409
