### ISSUE TITLE
Error in reading corpus database

### ISSUE THREAD

**Issue by czopluoglu** [unDocUMeantIt/koRpus#33]
I donwloaded the following file from this link (https://wortschatz.uni-leipzig.de/en/download/English)

**eng_news_2020_1M.tar.gz**

Then, I run the following code; however, it returns an error message.

`LCC.en <- read.corp.LCC(here('data','eng_news_2020_1M.tar.gz'))`
 
```
Fetching needed files from LCC archive... done.
Warning messages:
1: In readLines(LCC.file.con, n = n) :
  invalid input found on input connection 'C:\Users\cengiz\AppData\Local\Temp\RtmpWiHf2g\koRpus.LCC575c134d78b1/eng_news_2020_1M/eng_news_2020_1M-words.txt'
2: In readLines(LCC.file.con, n = n) :
  incomplete final line found on 'C:\Users\cengiz\AppData\Local\Temp\RtmpWiHf2g\koRpus.LCC575c134d78b1/eng_news_2020_1M/eng_news_2020_1M-words.txt'
3: In matrix(unlist(strsplit(rL.words, "\t")), ncol = 3, byrow = TRUE,  :
  data length [133] is not a sub-multiple or multiple of the number of rows [45]
4: In create.corp.freq.object(matrix.freq = table.words, num.running.words = num.running.words,  :
  NAs introduced by coercion
```

Is there a way to fix this? I am using Windows PC.

Thank you.

**Comment by czopluoglu** [comment]
I also realized another user opened a similar issue (#20 ).

This is certainly an encoding issue in Windows. There are special characters in the word.txt file that is causing the issue. I did some debugging and wrote a code to return the position of these characters causing the error. I am cleaning them one by one from the word.txt file, but this is so painful. That's why I opened the issue if you have come up with a solution.

I tried different encoding styles, but nothing works.

Thank you again.

**Comment by unDocUMeantIt** [comment]
hi,
thanks for reporting the issue -- again ;)

perhaps we can continue the debugging where we left off two years ago. i.e., when the person who originally reported the issue lost interest, i was unable to actually fix anything.

could you perhaps try what i [suggested last](https://github.com/unDocUMeantIt/koRpus/issues/20#issuecomment-536293425) when manually importing the files from the unpacked LCC archive, and wrap `readLines()` like `enc2utf8(readLines(...))`?

as soon as we found a workaround i can fix it in the package.

**Comment by unDocUMeantIt** [comment]
this is a long shot, but could you please try with this version?

```r
devtools::install_github("unDocUMeantIt/koRpus", ref="LCC")
```

i've changed how `read.copr.LCC()` uses the given encoding, i.e., not when specifing the file connection (which might lead to re-encoding of content) but with `readLines()`.

**Comment by czopluoglu** [comment]
This worked! Thank you.

**Comment by unDocUMeantIt** [comment]
cool. thanks for testing, i'll merge this patch into the develop branch so it will be released with the next stable release.
