### ISSUE TITLE
Can I use the udpipe annotated results?

### ISSUE THREAD

**Issue by seonghobae** [unDocUMeantIt/koRpus#34]
Hello,
Can I use the udpipe annotated results with ```udpipe::udpipe_annotate()```?
If I can, Can you show me the example?

Best,
Seongho

**Comment by unDocUMeantIt** [comment]
hi,

this is currently not supported out of the box. looks like a worthwhile feature request ;)

the tagged data frame would have to be converted into a compatible set of columns and the tagset used would have to be checked for compatibility with koRpus' language packages.

in theory, `koRpus::readTagged()` should be straight forward, then.

**Comment by unDocUMeantIt** [comment]
i was now able to check this, and at least with english texts it works out of the box:

```r
library(udpipe)
library(koRpus.lang.en)
model <- udpipe_download_model(language="english")
ud_en <- udpipe_load_model(model$file_model)
x <- udpipe_annotate(ud_en, x="This is my sample text.")
x_kRp <- readTagged(
    as.data.frame(x),
    lang="en",
    tagger="manual",
    doc_id=as.data.frame(x)[1,"doc_id"],
    mtx_cols=c(
        token="token",
        tag="xpos",
        lemma="lemma"
    )
)
```

`x_kRp` can now be used with `koRpus`.
