### ISSUE TITLE
Getting "Awww, this should not happen" error even though the sys.tt.call runs sucessfully

### ISSUE THREAD

**Issue by maxreb** [unDocUMeantIt/koRpus#36]
I am using koRpus to read a list of textfiles to analyze thoses textes. 
Running on Windows 10 with R 4.0.5 x64 using R-Studio 1.4.1717 and koRpus v0.13-8
When I run my R script I allways get this error message:

> sys.tt.call:   perl  C:\TreeTagger\cmd\utf8-tokenize.perl  -a C:/TreeTagger/lib/german-abbreviations "S:\XX\Politik\tt\ID_15010101.txt" |   C:\TreeTagger\\bin\tree-tagger.exe C:\TreeTagger\lib\german.par -token -lemma -sgml -pt-with-lemma -quiet  
> 
> Error: Awww, this should not happen: TreeTagger didn't return any useful data.
>   This can happen if the local TreeTagger setup is incomplete or different from what presets expected.
>   You should re-run your command with the option 'debug=TRUE'. That will print all relevant configuration.
>   Look for a line starting with 'sys.tt.call:' and try to execute the full command following it in a
>   command line terminal. Do not close this R session in the meantime, as 'debug=TRUE' will keep temporary
>   files that might be needed.
>   If running the command after 'sys.tt.call:' does fail, you'll need to fix the TreeTagger setup.
>   If it does *not* fail but produce a table with proper results, please contact the author!

When I run the sys.tt.call manually i get the following result, which looks good for me:

> Die     ART     die
> Parteien        NN      Partei
> der     ART     die
> Bundesrepublik  NN      Bundesrepublik
> Deutschland     NE      Deutschland
> [...]

This is my code:
```
install.packages("koRpus")
install.koRpus.lang("de")
library(koRpus.lang.de)

setwd("S:/XX/txt-Dateien_utf8/Politik/tt")

LCC.en <- read.corp.LCC("S:/XX/deu_news_2020_100K.tar.gz")

df.results <- data.frame ("0", "0")
names(df.results)<-c("ID", "pmio.mean")
fileNames <- Sys.glob("*.txt")

for (fileName in fileNames) {
#text-ID als Konstante
k.1 <- fileName
tagged.text1 <- treetag(
  fileName,
  treetagger="manual",
  debug=TRUE,
  lang="de",
  TT.options=list(
    path="C:/TreeTagger/",
    preset="de"
  ),
  doc_id=fileName
)
# Frequenzanalyse 
freq.analysis.res <- freq.analysis(tagged.text1, corp.freq=LCC.en)
# Statistische Analyse der Daten, Mean von pmio extrahieren
as(freq.analysis.res, "kRp.text")
l <- corpusFreq(freq.analysis.res)
l.1 <- (l$frq.pmio$summary.all$summary)
l.1 <- unname(l.1)
print(k.1)
k <- print(l.1[4])
k.2 <- toString(k, width = NULL)
# die Ergebnisse zum Ergebnissdokument hinzufÃ¼gen
de<-data.frame(k.1, k.2)
names(de)<-c("ID","pmio.mean")
df.results <- rbind(df.results, de)
}

print(df.results)
```

Do you have any idea what could be the problem?

**Comment by unDocUMeantIt** [comment]
FTR, which version of `koRpus` are you using?

when dealing with whole corpora instead of single texts, i would recommend trying the `tm.plugin.koRpus` package, which was designed for this task (it uses `koRpus`, which only reads on file at a time, but can process even recursive directory structures of texts). this will probably not solve the issue at hand, though.

when dealing with problems on windows, they often turn out to be related to character encoding issues. it only takes one single unknown character in a text to result in a distorted matrix, and that's it. the first thing i would check here is whether the issue occurs for all of the read texts or just for a subset of them. reduce your code to just the `treetag()` call and add like `message(fileName)` to see where it's at. does it process any of the texts without errors?

**Comment by unDocUMeantIt** [comment]
is the problem exclusive to the text in file `ID_15010101.txt`, is it also a few other texts or is it all of your texts?

**Comment by maxreb** [comment]
Hi, first of all, thanks for you answers!
Yesterday I had time to work on that problem again and I found out that it seemd to be an encoding issue. After converting my txt files from UTF8 to ANSI the TreeTagger worked. But now I stuck on another problem. The code you see above is from one of my colleagues who uses an Mac and everything works there but I get the following error

> Error in (function (classes, fdef, mtable) :
>  unable to find an inherited method for function 'freq.analysis' for signature '"matrix"'

on this line:
`freq.analysis.res <- freq.analysis(tagged.text1, corp.freq=LCC.en)`

It seems like the function does not exists for matrices but why does it work on the computer of my collegue? I also tried to install older versions of koRpus (I added the version number in the first post) but this didn't work either.

**Comment by unDocUMeantIt** [comment]
try without `debug=TRUE`, i guess

**Comment by maxreb** [comment]
Oh wow, stupid me ~~ Yes, now everything works as excepted, thanks a lot. 
I don't know if you want this issue to be kept open because of the ANSI/UTF8 thing? If you need anything from me, I will send you the data, otherwise from my side you could close this issue :)

**Comment by unDocUMeantIt** [comment]
i think i'll close this ticket for now. if there's something in particular that you think i can fix within the package, feel free to open a new ticket right away ;)
