### ISSUE TITLE
Flesch Formula multiplier

### ISSUE THREAD

**Issue by miezmiuremiezutschi** [unDocUMeantIt/koRpus#38]
I noticed that the multiplier of the average syllable length in the Documentation of koRpus (page 25 and 87) is 84.6. On Wikipedia and in the original 1948 paper by Flesch it was 85.6.

**Comment by unDocUMeantIt** [comment]
can you please be more specific regarding your sources? my copy of "a new readability yardstick" (flesch, 1948) contains 84.6, as does the [english](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests#Flesch_reading_ease) and [german](https://de.wikipedia.org/wiki/Lesbarkeitsindex#Flesch-Reading-Ease) wikipedia on the reading ease formula.
